### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by Avwqs** [SuperMonster003/Ant_Forest#1]
07:21:17.550/E: TypeError: rankListReady is not a function, it is undefined. (/storage/emulated/0/脚本/Ant_Forest_Project/Tools/!Ant_Forest.js#934)
TypeError: rankListReady is not a function, it is undefined.
    at restartAlipayToHeroList (/storage/emulated/0/脚本/Ant_Forest_Project/Tools/!Ant_Forest.js:934:0)
    at backToHeroList (/storage/emulated/0/脚本/Ant_Forest_Project/Tools/!Ant_Forest.js:925:0)
    at checkFriendsEnergy (/storage/emulated/0/脚本/Ant_Forest_Project/Tools/!Ant_Forest.js:520:0)
    at checkEnergy (/storage/emulated/0/脚本/Ant_Forest_Project/Tools/!Ant_Forest.js:433:0)
    at antForest (/storage/emulated/0/脚本/Ant_Forest_Project/Tools/!Ant_Forest.js:52:0)
    at /storage/emulated/0/脚本/Ant_Forest_Project/Tools/!Ant_Forest.js:44:0

**Comment by SuperMonster003** [comment]
`927` ``rankListReady`` -> `conditionRankListReady`
`928` ``rankListReady`` -> `conditionRankListReady`

**Comment by SuperMonster003** [comment]
已于 `v1.4.10` - `2019/04/10` 修复此问题
