### ISSUE TITLE
EMUI9和Magic2.0解锁问题

### ISSUE THREAD

**Issue by djun90** [SuperMonster003/Ant_Forest#8]
大佬你好，我是酷安回你帖子的小寒寒。
手机荣耀magic2 解锁方式为上滑+6位数字密码。
出现的问题就是不会上滑，尝试按照问题里面MIUI的解锁问题的方法也无效。
但我自己从别的项目找到了解锁方法，来自miui的，已多次测试没有问题，望添加。
if (!device.isScreenOn() || desc("快捷方式").exists()) {
    //曲线解锁 miui锁屏滑动不能唤出密码输入 通过下拉通知栏点击时间进入密码解锁 
    device.wakeUp();
    //下拉状态栏 
    swipe(500, 30, 650, 1300, 800);
    sleep(400);
    //点击时间 
    click(100, 120);
    //解锁 密码556666
    desc(5).findOne().click();
    desc(5).findOne().click();
    desc(6).findOne().click();
    desc(6).findOne().click();
    desc(6).findOne().click();
    desc(6).findOne().click();
}

**Comment by SuperMonster003** [comment]
感谢反馈
我上午刚修改了解锁模块逻辑 今晚会发布新版本 如果此版本依然存在滑动失败问题 我会考虑把你提供的代码整合进来
主要我更希望用比较通用的方式实现功能 尽量避免在代码中出现过多的特殊个例
请关注今晚的版本更新

**Comment by SuperMonster003** [comment]
已于 `v1.5.14` - `2019/04/22` 尝试修复此问题

**Comment by djun90** [comment]
解锁布局抓取报错，抓取布局的时候可以上滑了，上滑后就报错了。
自动解锁就是无法确定解锁方式了。 
20:08:23.059/E: Thread[ScriptThread-62[/storage/emulated/0/脚本/Ant_Forest-master/Ant_Forest_Project/Tools/Inspect_Lock_Screen_Layout.js] (Spawn-3),5]: TypeError: Cannot call method "exists" of null (/storage/emulated/0/脚本/Ant_Forest-master/Ant_Forest_Project/Tools/Inspect_Lock_Screen_Layout.js#123)
TypeError: Cannot call method "exists" of null
    at /storage/emulated/0/脚本/Ant_Forest-master/Ant_Forest_Project/Tools/Inspect_Lock_Screen_Layout.js:123:0
    at check (/storage/emulated/0/脚本/Ant_Forest-master/Ant_Forest_Project/Tools/Inspect_Lock_Screen_Layout.js:264:0)
    at dismissLayer (/storage/emulated/0/脚本/Ant_Forest-master/Ant_Forest_Project/Tools/Inspect_Lock_Screen_Layout.js:123:0)
    at /storage/emulated/0/脚本/Ant_Forest-master/Ant_Forest_Project/Tools/Inspect_Lock_Screen_Layout.js:45:0

**Comment by SuperMonster003** [comment]
好 明天继续尝试修复 最迟下午会发布试修版本

**Comment by djun90** [comment]
下午了，催更催更 嘻嘻

**Comment by SuperMonster003** [comment]
😃
请使用新版锁屏布局工具将布局信息发送给我
[Inspect_Lock_Screen_Layout.zip](https://github.com/SuperMonster003/Ant_Forest/files/3106237/Inspect_Lock_Screen_Layout.zip)

**Comment by djun90** [comment]
这次没上滑
[!Debug_Info.zip](https://github.com/SuperMonster003/Ant_Forest/files/3106281/Debug_Info.zip)

**Comment by SuperMonster003** [comment]
收到 正在分析 稍后发布试修版

**Comment by SuperMonster003** [comment]
😃
可尝试此试修版解锁模块  
放在Modules目录中  
[MODULE_UNLOCK.zip](https://github.com/SuperMonster003/Ant_Forest/files/3106625/MODULE_UNLOCK.zip)  
如果此版本失败的话 请再次反馈 并建议重新使用以下新版本锁屏布局工具 按步骤操作 (主要是手机的震动反馈相关提示要看明确) 然后再次将调试信息发送给我
[Inspect_Lock_Screen_Layout.zip](https://github.com/SuperMonster003/Ant_Forest/files/3106635/Inspect_Lock_Screen_Layout.zip)

**Comment by djun90** [comment]
上滑了 不输入密码 git一直传不上去


 
---原始邮件---
发件人: "SuperMonster003"<notifications@github.com>
发送时间: 2019年4月23日(星期二) 下午4:43
收件人: "SuperMonster003/Ant_Forest"<Ant_Forest@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"djun90"<812148374@qq.com>;
主题: Re: [SuperMonster003/Ant_Forest] EMUI9和Magic2.0解锁问题 (#8)



😃
 可尝试此试修版解锁模块
 放在Modules目录中
 MODULE_UNLOCK.zip
 如果此版本失败的话 请再次反馈 并建议重新使用以下新版本锁屏布局工具 按步骤操作 (主要是手机的震动反馈相关提示要看明确) 然后再次将调试信息发送给我
 Inspect_Lock_Screen_Layout.zip

**Comment by djun90** [comment]
https://www.lanzous.com/i3vu62h

**Comment by SuperMonster003** [comment]
收到 晚上试修

**Comment by SuperMonster003** [comment]
[MODULE_UNLOCK.zip](https://github.com/SuperMonster003/Ant_Forest/files/3107659/MODULE_UNLOCK.zip)

**Comment by djun90** [comment]
ok了 没有问题了，谢谢大佬
